# Numpy



#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [43]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [44]:
np.__version__

'1.21.5'

In [45]:
np.show_config

<function numpy.__config__.show>

#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [46]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [47]:
np.size((3,5,2))

3

In [48]:
x=np.array([4,5,6],dtype=np.float32)
x.itemsize

4

#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [49]:
#python -c "import numpy; numpy.info(numpy.add)"

In [50]:
arr=np.zeros((2,3,3))
np.info(arr)

class:  ndarray
shape:  (2, 3, 3)
strides:  (72, 24, 8)
itemsize:  8
aligned:  True
contiguous:  True
fortran:  False
data pointer: 0x55d66a550c60
byteorder:  little
byteswap:  False
type: float64


#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [51]:
x=np.zeros(10)
x[4]=1
x

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [52]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [53]:
x=np.arange(11)
x[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [54]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [55]:
x=np.array([1,2,0,0,4,0])
np.nonzero(x)

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [56]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [57]:
np.random.random((3,3,3))

array([[[0.46135458, 0.04593898, 0.91456689],
        [0.08468692, 0.41342857, 0.97627277],
        [0.61687253, 0.00491557, 0.63946033]],

       [[0.52484074, 0.96564283, 0.9989152 ],
        [0.60177479, 0.14212545, 0.77164812],
        [0.46905459, 0.21423035, 0.04900481]],

       [[0.77210612, 0.92063503, 0.31104792],
        [0.01857352, 0.42308079, 0.38016711],
        [0.28544403, 0.08240427, 0.76585011]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [58]:
a=np.random.randint(1,high=30,size=(1,10,10))
print(a)
print(np.max(a))
print(np.min(a))

[[[10 17  1  5 27 20 21 26 10  8]
  [25 11 27 25  1 10 24 19 21  5]
  [28 17  9 22 22  7 13 23 14  2]
  [27 22  8 20 18  6 28 13 26  2]
  [10 20  4 23 15 22  4  7  3 26]
  [10 15 20 28 24 15  8 26 16  6]
  [14  5  2 18  4  2  2 27 20 17]
  [20 26 26 18 19  3 18  5 17 18]
  [28 25 20  3 13 17 25 24  9 24]
  [ 7 19 29 10 25 28  9  1  9 15]]]
29
1


#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [59]:
a=np.random.randint(1,high=30,size=(1,3,3))
print(a)
a.mean()

[[[ 3  4 22]
  [17 17 25]
  [ 1 17 23]]]


14.333333333333334

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [60]:
a=np.ones((10,10))
a[1:-1,1:-1]=0
print(a)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [61]:
a=np.ones((10,10))
np.pad(a,1)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [62]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [63]:
np.diag((1,2,3,4,5))

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [64]:
a=np.ones((8,8))
a[1::2,::2]=0
a[::2,1::2]=0
a

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [65]:
np.unravel_index(100,(6,7,8))

(1, 5, 4)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [66]:
Z = np.tile(np.array([[0,1],[1,0]]), (4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [67]:
a=np.random.randint(5,high=20,size=(1,5,5))
n=(a-np.max(a)/np.max(a)-np.min(a))
print(a)
print(n)

[[[ 6  5 11 11 18]
  [16 19 19 11 16]
  [12 18 13 13 14]
  [ 5 17 16  8 18]
  [10 12 10 10  8]]]
[[[ 0. -1.  5.  5. 12.]
  [10. 13. 13.  5. 10.]
  [ 6. 12.  7.  7.  8.]
  [-1. 11. 10.  2. 12.]
  [ 4.  6.  4.  4.  2.]]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [68]:
color = np.dtype([("r", np.ubyte, 1),("g", np.uintc, 1),("b", np.uint, 1),("a", np.ulonglong, 1)])


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  """Entry point for launching an IPython kernel.


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [69]:
Z = np.ones((5,3)) @ np.ones((3,2))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [70]:
Z = np.arange(11)
Z[(3 < Z) & (Z <= 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [71]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [72]:
Z=4
print(Z**Z)
print(2 << Z >> 2)
print(Z <- Z)
print(1j*Z)
print(Z/1/1)
print(Z<Z>Z)
#all expressions are legal

256
8
False
4j
4.0
False


#### 28. What are the result of the following expressions?


```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [73]:
print(np.array(0) / np.array(0)) 
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [74]:
a= np.random.uniform(-20,10,10)
print (np.copysign(np.ceil(np.abs(a)), a))

[  1.   3. -17.  -4.  -6. -13. -13.   2.  -6. -11.]


#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [75]:
a = np.random.randint(1,3,3)
b = np.random.randint(1,3,3)
print(a)
print(b)
print(np.intersect1d(a,b))

[1 2 1]
[1 2 1]
[1 2]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

In [76]:
a = np.seterr(all="ignore")
n=np.ones(1)/0
a=np.seterr(**a)

In [77]:
with np.errstate(divide='ignore'):
    a=np.ones(1)/0

#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [78]:
np.sqrt(-1) == np.emath.sqrt(-1)#False

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [79]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print(yesterday)
print(today)
print(tomorrow)

2022-03-27
2022-03-28
2022-03-29


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [80]:
a=np.arange('2016-07','2016-08',dtype='datetime64[D]')
print(a)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [81]:
a= np.ones(3)*1
b= np.ones(3)*2
c= np.ones(3)
print(a)
print(b)
print(c)
np.add(a,b,out=b)
np.divide(a,2,out=b)
np.negative(a,out=a)
np.multiply(a,b,out=c)
c

[1. 1. 1.]
[2. 2. 2.]
[1. 1. 1.]


array([-0.5, -0.5, -0.5])

#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [82]:
a= np.random.uniform(0,10,10)
print (a-a%1)
print (np.floor(a))
print (np.ceil(a))
print (a.astype(int))
print (np.trunc(a))

[2. 8. 8. 4. 8. 9. 9. 1. 8. 2.]
[2. 8. 8. 4. 8. 9. 9. 1. 8. 2.]
[ 3.  9.  9.  5.  9. 10. 10.  2.  9.  3.]
[2 8 8 4 8 9 9 1 8 2]
[2. 8. 8. 4. 8. 9. 9. 1. 8. 2.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [83]:
a=np.zeros((5,5))
a=a+np.arange(5)
print(a)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [84]:
def fun():
  for i in range(10):
    yield i
a=np.fromiter(fun(),dtype=int,count=-1)
print(a)

[0 1 2 3 4 5 6 7 8 9]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [85]:
Z = np.linspace(0,1,11,endpoint=False)[1:]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [86]:
a= np.random.random(10)
a.sort()
print(a)

[0.03085427 0.17985809 0.44618463 0.63695387 0.71898843 0.81041932
 0.83397371 0.84443227 0.84516278 0.91266334]


#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [87]:
a=np.random.randint(10,100,10)
print(a)
np.add.reduce(a)

[81 34 29 38 22 28 32 91 50 86]


491

#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [88]:
a=np.random.randint(10,100,10)
b=np.random.randint(10,100,10)
print(a)
print(b)
c=np.allclose(a,b)
print(c)
c=np.array_equal(a,b)
print(c)

[99 59 76 72 19 52 92 33 98 40]
[33 21 71 21 48 90 32 91 24 18]
False
False


#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

In [89]:
a=np.zeros(3)
a.flags.writeable=False
a[0]=1

ValueError: ignored

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [94]:
n= np.random.random((10,2))
a,b = n[:,0], n[:,1]
i= np.sqrt(a**2+b**2)
j= np.arctan2(b,a)
print(i)
print(j)

[1.07371392 0.47390971 0.24534556 1.16298401 0.77760405 0.63446878
 0.37567361 0.70019374 1.13185613 0.65383774]
[0.44348908 0.21593421 0.90496315 0.57767214 0.92004031 1.27848785
 0.48443594 0.17775058 0.57817695 0.79548418]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [95]:
a=np.random.random(10)
print(a)
a[a.argmax()] = 0
print(a)

[0.75377545 0.2445514  0.44525424 0.89888536 0.92979189 0.28670234
 0.21307453 0.22794661 0.71058576 0.56020364]
[0.75377545 0.2445514  0.44525424 0.89888536 0.         0.28670234
 0.21307453 0.22794661 0.71058576 0.56020364]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

In [100]:
a= np.zeros((3,3), [('x',float),('y',float)])
a['x'],a['y']=np.meshgrid(np.linspace(0,1,3),np.linspace(0,1,3))
print(a)

[[(0. , 0. ) (0.5, 0. ) (1. , 0. )]
 [(0. , 0.5) (0.5, 0.5) (1. , 0.5)]
 [(0. , 1. ) (0.5, 1. ) (1. , 1. )]]


####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

In [101]:
a= np.arange(8)
b=a+ 0.5
c= 1.0/np.subtract.outer(a,b)
print(np.linalg.det(c))

3638.163637117973


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [102]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [103]:
np.set_printoptions(threshold=float("inf"))
Z = np.zeros((10,10))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [105]:
a=np.arange(100)
b=np.random.uniform(0,100)
i=(np.abs(a-b)).argmin()
print(a[i])

82


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

In [108]:
n= np.random.random((10,2))
a,b= np.atleast_2d(n[:,0], n[:,1])
d=np.sqrt((a-a.T)**2 + (b-b.T)**2)
print(d)

[[0.         0.44941491 0.2057666  0.48098897 0.41810928 0.30632931
  0.38058819 0.58156835 0.55758754 0.16961529]
 [0.44941491 0.         0.47705179 0.67953358 0.84086267 0.71318233
  0.60456547 0.79470941 0.1692359  0.41344632]
 [0.2057666  0.47705179 0.         0.68671134 0.55911462 0.47397558
  0.58626834 0.78678497 0.52370844 0.36410922]
 [0.48098897 0.67953358 0.68671134 0.         0.43748851 0.35161971
  0.1005152  0.1161408  0.84517781 0.33847902]
 [0.41810928 0.84086267 0.55911462 0.43748851 0.         0.13076408
  0.39083232 0.45808549 0.96901048 0.4361456 ]
 [0.30632931 0.71318233 0.47397558 0.35161971 0.13076408 0.
  0.28481774 0.40166286 0.8460112  0.30572258]
 [0.38058819 0.60456547 0.58626834 0.1005152  0.39083232 0.28481774
  0.         0.20888522 0.76641458 0.24041753]
 [0.58156835 0.79470941 0.78678497 0.1161408  0.45808549 0.40166286
  0.20888522 0.         0.9608697  0.44926539]
 [0.55758754 0.1692359  0.52370844 0.84517781 0.96901048 0.8460112
  0.76641458 0.960869

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [110]:
a= np.arange(10, dtype=np.int32)
a=a.astype(np.float32)
print(a)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [112]:
from io import StringIO
f= StringIO("""1, 2, 3, 4, 5\n
                6,  ,  , 7, 8\n
                 ,  , 9,10,11\n""")
a= np.genfromtxt(f, delimiter=",", dtype=np.int)
print(a)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  """


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [114]:
a= np.arange(9).reshape(3,3)
for i, j in np.ndenumerate(a):
    print(i,j)
for i in np.ndindex(a.shape):
    print(i, a[i])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

In [116]:
a,b=np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
c=np.sqrt(a*b+a*b)
sigma, mu =1.0,0.0
d= np.exp(-((c-mu)**2/(2.0*sigma**2)))
print(d)

[[0.36787944 0.45942582 0.57375342 0.71653131 0.89483932        nan
         nan        nan        nan        nan]
 [0.45942582 0.54610814 0.64914526 0.77162295 0.91720915        nan
         nan        nan        nan        nan]
 [0.57375342 0.64914526 0.73444367 0.83095039 0.9401382         nan
         nan        nan        nan        nan]
 [0.71653131 0.77162295 0.83095039 0.89483932 0.96364044        nan
         nan        nan        nan        nan]
 [0.89483932 0.91720915 0.9401382  0.96364044 0.98773022        nan
         nan        nan        nan        nan]
 [       nan        nan        nan        nan        nan 0.98773022
  0.96364044 0.9401382  0.91720915 0.89483932]
 [       nan        nan        nan        nan        nan 0.96364044
  0.89483932 0.83095039 0.77162295 0.71653131]
 [       nan        nan        nan        nan        nan 0.9401382
  0.83095039 0.73444367 0.64914526 0.57375342]
 [       nan        nan        nan        nan        nan 0.91720915
  0.77162295 

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in sqrt
  


#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

In [121]:
n = 3
p = 3
a = np.zeros((n,n))
np.put(a, np.random.choice(range(n*n), p, replace=False),1)
print(a)

[[0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]]


#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [122]:
x= np.random.rand(5, 10)
y=x-x.mean(axis=1, keepdims=True)
print(y)

[[-0.46540789 -0.08169909 -0.17023974 -0.28052272  0.40066027  0.19983851
  -0.01878954  0.41782589  0.14204691 -0.14371258]
 [ 0.26211546 -0.07515693 -0.23869317  0.21568042  0.33881828  0.44243711
  -0.09174022 -0.31978025 -0.2767651  -0.25691561]
 [ 0.04657613  0.46401221  0.17228754  0.16340562 -0.26869266 -0.2294242
   0.14593642 -0.05673243 -0.24012727 -0.19724137]
 [-0.18028771  0.51570613 -0.27963593  0.16815218 -0.0104449   0.44454461
  -0.21904246  0.10499141 -0.27976658 -0.26421675]
 [ 0.10378991  0.36303765  0.30929239 -0.09862853 -0.06902528 -0.42698413
  -0.36643261 -0.34085088  0.40620147  0.11960003]]


#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [124]:
a= np.random.randint(0,5,(3,3))
print(a)
print(a[a[:,1].argsort()])

[[0 0 4]
 [4 3 1]
 [4 0 0]]
[[0 0 4]
 [4 0 0]
 [4 3 1]]


#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

In [127]:
a=np.random.randint(0,3,(3,3))
print(a)
print((~a.any(axis=0)).any())

[[0 2 1]
 [1 0 0]
 [1 1 0]]
False


#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

In [128]:
a= np.random.uniform(0,1,10)
b= 0.5
c=a.flat[np.abs(a-b).argmin()]
print(c)

0.5105045566186026


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

In [129]:
a=np.arange(3).reshape(3,1)
b=np.arange(3).reshape(1,3)
c= np.nditer([a,b,None])
for x,y,z in c: z[...] = x + y
print(c.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

In [130]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

a= NamedArray(np.arange(10), "range_10")
print (a.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

In [135]:
a=np.ones(10)
i=np.random.randint(0,len(Z),20)
a+= np.bincount(i, minlength=len(a))
print(a)


[3. 3. 1. 3. 3. 3. 3. 4. 3. 4.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

In [136]:
x= [1,2,3,4,5,6]
i= [1,3,9,3,4,1]
a= np.bincount(x)
print(a)

[0 1 1 1 1 1 1]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

In [145]:
a=np.random.randint(0,10,(3,4,3,4))
sum=a.sum(axis=(-2,-1))
print(sum)

[[55 43 67 71]
 [55 44 61 59]
 [54 52 54 51]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

In [146]:
d=np.random.uniform(0,1,100)
s=np.random.randint(0,10,100)
d_sums=np.bincount(s, weights=d)
d_counts=np.bincount(s)
d_means=d_sums/d_counts
print(d_means)

[0.51934959 0.57015434 0.66522959 0.4923932  0.29723856 0.5568051
 0.3664667  0.51692719 0.43475791 0.52547304]


#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

In [147]:
a = np.random.uniform(0,1,(3,3))
b = np.random.uniform(0,1,(3,3))
np.sum(a * b.T, axis=1)

array([0.83158877, 0.749413  , 1.26475086])

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

In [148]:
z=np.array([1,2,3,4,5])
n=3
k=np.zeros(len(z) + (len(z)-1)*(n))
k[::n+1]=z
print(k)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

In [149]:
a = np.ones((5,5,3))
b = 2*np.ones((5,5))
print(a * b[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

In [150]:
a= np.arange(25).reshape(5,5)
a[[0,1]] =a[[1,0]]
print(a)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

In [151]:
n=np.random.randint(0,100,(10,3))
a=np.roll(n.repeat(2,axis=1),-1,axis=1)
a=a.reshape(len(a)*3,2)
a=np.sort(a,axis=1)
b=a.view( dtype=[('p0',a.dtype),('p1',a.dtype)] )
b=np.unique(b)
print(b)

[( 5, 74) ( 5, 87) ( 7, 60) ( 7, 68) ( 8, 62) ( 8, 75) (10, 77) (10, 80)
 (28, 50) (28, 62) (31, 47) (31, 75) (36, 49) (36, 72) (47, 75) (49, 72)
 (50, 62) (51, 81) (51, 95) (60, 68) (62, 75) (67, 67) (67, 69) (68, 78)
 (68, 81) (74, 87) (77, 80) (78, 81) (81, 95)]


#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

In [ ]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

In [160]:
def mov(a,n=3):
  r=np.cumsum(a,dtype=float)
  r[n:]=r[n:]-r[:-n]
  return r[n-1:]/n
b=np.arange(20)
print(mov(b,n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

In [163]:
a=np.random.randint(0,2,100)
np.logical_not(a,out=a)

a=np.random.uniform(-1.0,1.0,100)
np.negative(a,out=a)

array([ 3.29045994e-01, -7.34279334e-01, -6.80555219e-01, -1.38774785e-01,
       -7.56476767e-01,  9.43730735e-01, -9.08248493e-01, -5.47030142e-01,
        5.57499013e-01,  9.89466394e-01,  3.03543511e-01,  1.43515215e-01,
       -5.89065562e-01,  3.11827353e-01,  8.54497304e-01,  1.03035638e-01,
       -3.51215293e-01,  8.68177865e-01, -8.69848811e-01,  2.62513263e-01,
        2.79026197e-01,  5.85992766e-01, -3.02229811e-01, -4.36668642e-01,
        4.60290843e-01,  5.04233449e-01, -1.36911266e-02,  2.24246766e-01,
        4.92999965e-01,  7.90140670e-01,  8.49171454e-01, -4.04381298e-01,
       -5.83577954e-02, -9.67493096e-01,  3.24367360e-01, -7.79480316e-01,
        1.65052216e-01, -3.27469897e-02,  6.63816897e-01, -1.15867624e-01,
       -3.13648524e-01,  8.82110263e-01,  2.69451894e-01, -3.06529072e-01,
       -2.33727856e-01,  6.62855597e-02, -8.73259670e-01,  2.27489190e-02,
       -1.81515672e-02, -4.83762701e-01, -8.39603533e-01,  3.20105427e-01,
       -3.59998401e-01,  

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

In [165]:
def distance(a, b, p):
    t=b - a
    l=(t**2).sum(axis=1)
    u=-((a[:,0]-p[...,0])*t[:,0] + (a[:,1]-p[...,1])*t[:,1]) / l
    u=u.reshape(len(u),1)
    d=a+u*t-p
    return np.sqrt((d**2).sum(axis=1))

a=np.random.uniform(-10,10,(10,2))
b=np.random.uniform(-10,10,(10,2))
p=np.random.uniform(-10,10,( 1,2))
print(distance(a, b, p))

[5.83792215 0.31914792 8.68623978 8.16546636 4.74954998 4.38662862
 2.23083077 9.89893764 6.33172897 4.52883615]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

In [166]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 1.00984456  5.46544961 12.43348113  4.01808164  2.57445082  6.22372976
   2.88245021  3.96597254 15.34322777  6.25417859]
 [ 2.4447334   9.89545758  6.06312807  1.26386464  0.13982346  2.35221232
   2.98458706  4.52753585  8.91247611  3.42340542]
 [ 5.01185197 17.34736259  4.80511389  3.31177911  4.64707971  4.13936388
  13.02848526  5.35756349  2.02884035  1.28333154]
 [19.85570725  2.675474    3.17135259 13.1336796  11.81911719 11.34810338
  15.91047564 11.13918231  3.44809659 15.12002543]
 [ 8.88812206  2.70595076 13.72967742 13.03191536 11.59679762 14.79646669
   1.72016832  4.93128943 18.70755181 15.25043145]
 [17.46067987  0.12361355  2.05615755 14.13403016 12.78421096 13.36492332
  10.74487689 10.29112741  8.41880152 16.18813927]
 [ 4.39839985  5.18179529  9.38433402  5.49518042  4.07617071  6.94499637
   0.70489542  1.3303834  12.94499975  7.68366929]
 [17.70869093  2.53002345  0.87640196 12.4393091  11.10703712 11.18960954
  13.32677472  9.58914237  5.35463419 14.45985019]


#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [168]:
from numpy.lib import stride_tricks

a=np.arange(1,15,dtype=np.uint32)
b=stride_tricks.as_strided(a,(11,4),(4,4))
print(b)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

In [170]:
a=np.random.uniform(0,1,(10,10))
u,s,v=np.linalg.svd(a)
r=np.sum(s>1e-10)
print(r)

10


#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

In [171]:
a= np.random.randint(0,10,50)
print(np.bincount(a).argmax())

0


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [172]:
a=np.random.randint(0,5,(10,10))
n=3
i=1+(a.shape[0]-3)
j=1+(a.shape[1]-3)
c=stride_tricks.as_strided(a,shape=(i,j,n,n),strides=a.strides+a.strides)
print(c)

[[[[4 4 3]
   [2 4 3]
   [2 3 1]]

  [[4 3 4]
   [4 3 4]
   [3 1 3]]

  [[3 4 0]
   [3 4 4]
   [1 3 2]]

  [[4 0 2]
   [4 4 0]
   [3 2 3]]

  [[0 2 4]
   [4 0 4]
   [2 3 3]]

  [[2 4 2]
   [0 4 3]
   [3 3 4]]

  [[4 2 0]
   [4 3 1]
   [3 4 3]]

  [[2 0 2]
   [3 1 4]
   [4 3 1]]]


 [[[2 4 3]
   [2 3 1]
   [1 4 0]]

  [[4 3 4]
   [3 1 3]
   [4 0 1]]

  [[3 4 4]
   [1 3 2]
   [0 1 3]]

  [[4 4 0]
   [3 2 3]
   [1 3 1]]

  [[4 0 4]
   [2 3 3]
   [3 1 1]]

  [[0 4 3]
   [3 3 4]
   [1 1 0]]

  [[4 3 1]
   [3 4 3]
   [1 0 2]]

  [[3 1 4]
   [4 3 1]
   [0 2 1]]]


 [[[2 3 1]
   [1 4 0]
   [1 0 0]]

  [[3 1 3]
   [4 0 1]
   [0 0 1]]

  [[1 3 2]
   [0 1 3]
   [0 1 1]]

  [[3 2 3]
   [1 3 1]
   [1 1 2]]

  [[2 3 3]
   [3 1 1]
   [1 2 1]]

  [[3 3 4]
   [1 1 0]
   [2 1 0]]

  [[3 4 3]
   [1 0 2]
   [1 0 0]]

  [[4 3 1]
   [0 2 1]
   [0 0 1]]]


 [[[1 4 0]
   [1 0 0]
   [1 3 0]]

  [[4 0 1]
   [0 0 1]
   [3 0 0]]

  [[0 1 3]
   [0 1 1]
   [0 0 0]]

  [[1 3 1]
   [1 1 2]
   [0 0 1]]

  [[3 1 1]
   

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

In [178]:
p,n=10,20
i=np.ones((p,n,n))
j=np.ones((p,n,1))
k=np.tensordot(i,j,axes=[[0,2],[0,1]])
print(k)


[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

In [181]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

In [183]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),np.arange(0, Z.shape[1], k), axis=1)
S

array([[16., 16., 16., 16.],
       [16., 16., 16., 16.],
       [16., 16., 16., 16.],
       [16., 16., 16., 16.]])

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [187]:
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])
    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  1 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  1 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 1 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 1 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 1 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 1 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0

#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

In [188]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
print (Z[np.argsort(Z)[-n:]])
print (Z[np.argpartition(-Z,n)[:n]])

[9995 9996 9997 9998 9999]
[9997 9996 9999 9998 9995]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

In [196]:
a= np.array([("Hello", 5.5, 2),("World", 9.3, 5)])
b= np.core.records.fromarrays(a.T,names='col1, col2, col3',formats = 'S8, f8, i8')
print(b)

[(b'Hello', 5.5, 2) (b'World', 9.3, 5)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

In [199]:
a= np.random.randint(0,5,(8,3))
b= np.random.randint(0,5,(2,2))
c= (a[..., np.newaxis, np.newaxis] ==b)
r=np.where(c.any((3,1)).all(1))[0]
print(r)

[0 1 2 5 7]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

In [ ]:
a=np.random.randint(0,5,(10,3))
print(a)
u=a[~(a[:,0,None]==Z[:,1:]).all(axis=1)]
print(U)

#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)